server {
    server_name clipclap.io;

    include /etc/nginx/snippets/clipclap-security-server.conf;

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/clipclap.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/clipclap.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    server_name www.clipclap.io;
    return 301 https://clipclap.io$request_uri;

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/clipclap.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/clipclap.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = clipclap.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name clipclap.io;
    return 404; # managed by Certbot
}

server {
    if ($host = www.clipclap.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name www.clipclap.io;
    return 404; # managed by Certbot
}
