import type { CropPlan, ShotLayout } from "../reframe/types";
import { cropWidthFor, tileWidthFor } from "../reframe/plan";
import type { VisualBox, VisualSample } from "./promote";

export type VisualProbeExec = (file: string, args: readonly string[], options?: Readonly<Record<string, unknown>>) => Promise<{ stdout: string; stderr: string }>;

export type VisualProbeInput = Readonly<{
  referencePath: string;
  /** Immutable delivered evidence, never generated by this observation run. */
  immutableReferencePath: string;
  highlightStart: number;
  cropPlan: CropPlan | null;
  assPath?: string;
  cues?: readonly unknown[];
  samples: readonly VisualSample[];
  contentThreshold?: number;
  exec: VisualProbeExec;
}>;

export type VisualProbeResult = Readonly<{
  approvedMomentRetained: number;
  approvedWindowOverlap: number;
  contentMatch: number;
  subtitleOverlap: number;
  requiredTextClipped: number;
  requiredSubjectClipped: number;
  focalFailures: number;
  visualMeasured: true;
}>;

type PixelBox = { x: number; y: number; w: number; h: number };
const OUT_W = 1080;
const OUT_H = 1920;
const EPSILON = 1e-6;

function finiteBox(value: VisualBox): void {
  if (![value.x, value.y, value.w, value.h].every(Number.isFinite) || value.x < 0 || value.y < 0 || value.w <= 0 || value.h <= 0 || value.x + value.w > 1 + EPSILON || value.y + value.h > 1 + EPSILON) throw new Error("invalid visual annotation");
}

function area(value: PixelBox): number { return Math.max(0, value.w) * Math.max(0, value.h); }
function overlap(a: PixelBox, b: PixelBox): number {
  const x = Math.max(0, Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x));
  const y = Math.max(0, Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y));
  return x * y;
}

function cropX(layout: ShotLayout, timestamp: number, center: number): number {
  if (layout.layout === "single") {
    const keyframes = layout.xs;
    if (!keyframes?.length) return layout.x;
    if (timestamp <= keyframes[0].t) return keyframes[0].x;
    for (let i = 1; i < keyframes.length; i += 1) {
      if (timestamp <= keyframes[i].t) {
        const previous = keyframes[i - 1];
        const fraction = (timestamp - previous.t) / Math.max(EPSILON, keyframes[i].t - previous.t);
        return previous.x + (keyframes[i].x - previous.x) * fraction;
      }
    }
    return keyframes[keyframes.length - 1].x;
  }
  if (layout.layout === "center") return layout.x;
  if (layout.layout === "split") return center;
  if (layout.layout === "stream") return center;
  return center;
}

function sourceToCrop(box: VisualBox, source: { width: number; height: number }, x: number, y: number, width: number, height: number, outY = 0, outHeight = OUT_H): PixelBox {
  const sourceBox: PixelBox = { x: box.x * source.width, y: box.y * source.height, w: box.w * source.width, h: box.h * source.height };
  return { x: (sourceBox.x - x) * OUT_W / width, y: outY + (sourceBox.y - y) * outHeight / height, w: sourceBox.w * OUT_W / width, h: sourceBox.h * outHeight / height };
}

function sourceToContain(box: VisualBox, source: { width: number; height: number }): PixelBox {
  const scale = Math.min(OUT_W / source.width, OUT_H / source.height);
  const renderedWidth = source.width * scale;
  const renderedHeight = source.height * scale;
  return { x: box.x * renderedWidth + (OUT_W - renderedWidth) / 2, y: box.y * renderedHeight + (OUT_H - renderedHeight) / 2, w: box.w * renderedWidth, h: box.h * renderedHeight };
}

function mapsFor(plan: CropPlan | null, timestamp: number): Array<{ map: (box: VisualBox) => PixelBox }> {
  if (!plan) return [{ map: (box) => sourceToCrop(box, { width: OUT_W, height: OUT_H }, 0, 0, OUT_W, OUT_H) }];
  if (!plan.source || !Number.isFinite(plan.source.width) || !Number.isFinite(plan.source.height) || plan.source.width <= 0 || plan.source.height <= 0) throw new Error("invalid visual crop plan");
  const source = plan.source;
  const shot = plan.shots.find((candidate) => timestamp >= candidate.start && timestamp < candidate.end) ?? plan.shots[plan.shots.length - 1];
  if (!shot) throw new Error("visual crop plan has no shot");
  const center = Math.max(0, (source.width - cropWidthFor(source.height)) / 2);
  if (shot.layout === "safe-fit") return [{ map: (box) => sourceToContain(box, source) }];
  if (shot.layout === "split") {
    const tile = tileWidthFor(source.height);
    return [
      { map: (box) => sourceToCrop(box, source, shot.top.x, 0, tile, source.height, 0, OUT_H / 2) },
      { map: (box) => sourceToCrop(box, source, shot.bottom.x, 0, tile, source.height, OUT_H / 2, OUT_H / 2) },
    ];
  }
  if (shot.layout === "stream" && plan.stream) {
    const geometry = plan.stream;
    return [
      { map: (box) => sourceToCrop(box, source, shot.cam.x, geometry.camCrop.y, geometry.camCrop.w, geometry.camCrop.h, 0, geometry.outCamH) },
      { map: (box) => sourceToCrop(box, source, shot.content.x, 0, geometry.contentCrop.w, source.height, geometry.outCamH, geometry.outContentH) },
    ];
  }
  const width = cropWidthFor(source.height);
  return [{ map: (box) => sourceToCrop(box, source, cropX(shot, timestamp, center), 0, width, source.height) }];
}

function annotatedVisibility(box: VisualBox, maps: ReturnType<typeof mapsFor>, source: CropPlan["source"] | null): number {
  if (!source) return 1;
  return Math.max(...maps.map(({ map }) => {
    const mapped = map(box);
    return overlap(mapped, { x: 0, y: 0, w: OUT_W, h: OUT_H }) / Math.max(EPSILON, area(mapped));
  }));
}

function parseBbox(output: string): PixelBox | null {
  const match = output.match(/x1\s*[:=]\s*(-?\d+).*?x2\s*[:=]\s*(-?\d+).*?y1\s*[:=]\s*(-?\d+).*?y2\s*[:=]\s*(-?\d+)/s);
  if (!match) return null;
  const [x1, x2, y1, y2] = match.slice(1).map(Number);
  if (![x1, x2, y1, y2].every(Number.isFinite) || x2 < x1 || y2 < y1 || x1 < 0 || y1 < 0 || x2 >= OUT_W || y2 >= OUT_H) throw new Error("visual subtitle bbox invalid");
  return { x: x1, y: y1, w: x2 - x1 + 1, h: y2 - y1 + 1 };
}

function outputBox(box: VisualBox): PixelBox {
  finiteBox(box);
  return { x: box.x * OUT_W, y: box.y * OUT_H, w: box.w * OUT_W, h: box.h * OUT_H };
}

function normalizedText(value: unknown): string {
  if (typeof value !== "string") return "";
  return value.replace(/\{[^}]*\}/g, "").normalize("NFKC").toLocaleLowerCase().replace(/\s+/g, " ").trim();
}

async function assertFrame(exec: VisualProbeExec, path: string, timestamp: number): Promise<void> {
  let result: { stdout: string; stderr: string };
  try {
    result = await exec("ffprobe", ["-show_entries", "stream=width,height,nb_read_frames", "-v", "error", "-ss", String(timestamp), "-i", path, "-select_streams", "v:0", "-read_intervals", "0%+0.05", "-count_frames", "-of", "json"], { timeout: 15_000, maxBuffer: 2 * 1024 * 1024 });
  } catch { throw new Error("visual probe frame unavailable"); }
  let parsed: { streams?: Array<{ width?: number; height?: number; nb_read_frames?: string }> };
  try { parsed = JSON.parse(result.stdout) as typeof parsed; } catch { throw new Error("visual probe frame parse failed"); }
  const stream = parsed.streams?.[0];
  if (stream?.width !== OUT_W || stream.height !== OUT_H || Number(stream.nb_read_frames ?? 0) < 1) throw new Error("visual probe frame geometry failed");
}

type FrameComparison = Readonly<{ similarity: number; difference: PixelBox | null }>;

function parseSimilarity(output: string): number {
  const match = output.match(/SSIM\s+Y\s*:\s*([0-9]+(?:\.[0-9]+)?)/i);
  const value = match ? Number(match[1]) : NaN;
  if (!Number.isFinite(value) || value < 0 || value > 1) throw new Error("visual comparison unavailable");
  return value;
}

async function compareFrames(exec: VisualProbeExec, actualPath: string, referencePath: string, timestamp: number, ignoredBoxes: readonly PixelBox[] = []): Promise<FrameComparison> {
  const masks = ignoredBoxes.map((box) => `drawbox=x=${Math.round(box.x)}:y=${Math.round(box.y)}:w=${Math.round(box.w)}:h=${Math.round(box.h)}:color=black:t=fill`).join(",");
  const prefix = masks ? `[0:v]${masks}[a];[1:v]${masks}[b];` : "";
  const inputs = masks ? "[a][b]" : "[0:v][1:v]";
  let similarity: { stdout: string; stderr: string };
  let difference: { stdout: string; stderr: string };
  try {
    similarity = await exec("ffmpeg", ["-nostdin", "-v", "info", "-ss", String(timestamp), "-i", actualPath, "-ss", String(timestamp), "-i", referencePath, "-filter_complex", `${prefix}${inputs}ssim=stats_file=-`, "-frames:v", "1", "-f", "null", "-"], { timeout: 15_000, maxBuffer: 2 * 1024 * 1024 });
    difference = await exec("ffmpeg", ["-nostdin", "-v", "info", "-ss", String(timestamp), "-i", actualPath, "-ss", String(timestamp), "-i", referencePath, "-filter_complex", `${prefix}${inputs}blend=all_mode=difference,bbox`, "-frames:v", "1", "-f", "null", "-"], { timeout: 15_000, maxBuffer: 2 * 1024 * 1024 });
  } catch { throw new Error("visual comparison unavailable"); }
  return { similarity: parseSimilarity(`${similarity.stdout}\n${similarity.stderr}`), difference: parseBbox(`${difference.stdout}\n${difference.stderr}`) };
}

/** Measures the frozen visual contract against actual sampled output. No
 * annotation, frame, geometry, or ASS probe failure is converted into zero. */
export async function measureVisualReplay(path: string, input: VisualProbeInput): Promise<VisualProbeResult> {
  if (!input.samples.length) throw new Error("visual annotation unavailable");
  if (!Number.isFinite(input.highlightStart) || input.highlightStart < 0 || !input.referencePath || !input.immutableReferencePath) throw new Error("visual immutable reference unavailable");
  if (!input.cropPlan && input.samples.some((sample) => sample.requiredSubjectBoxes.length > 0 || sample.requiredTextBoxes.length > 0 || sample.protectedExistingCaptionBoxes.length > 0)) throw new Error("visual crop plan unavailable");
  let subtitleOverlap = 0;
  let requiredTextClipped = 0;
  let requiredSubjectClipped = 0;
  let contentMismatch = 0;
  let sampledSimilarity = 1;
  for (const sample of input.samples) {
    if (!Number.isFinite(sample.timestamp) || sample.timestamp < 0) throw new Error("invalid visual annotation");
    const relativeTimestamp = sample.timestamp - input.highlightStart;
    if (relativeTimestamp < 0) throw new Error("visual sample outside highlight");
    for (const box of [...sample.requiredSubjectBoxes, ...sample.requiredTextBoxes, ...sample.protectedExistingCaptionBoxes]) finiteBox(box);
    if (sample.expectedSubtitleBox) finiteBox(sample.expectedSubtitleBox);
    await assertFrame(input.exec, path, relativeTimestamp);
    await assertFrame(input.exec, input.referencePath, relativeTimestamp);
    await assertFrame(input.exec, input.immutableReferencePath, relativeTimestamp);
    const maps = mapsFor(input.cropPlan, relativeTimestamp);
    const mutableBoxes = [sample.expectedSubtitleBox].filter((box): box is VisualBox => Boolean(box)).map(outputBox)
      .concat(sample.protectedExistingCaptionBoxes.flatMap((box) => maps.map(({ map }) => map(box))));
    const evidenceComparison = await compareFrames(input.exec, path, input.immutableReferencePath, relativeTimestamp, mutableBoxes);
    // Keep one unmasked comparison to measure the actual subtitle pixel bbox;
    // the masked comparison is only for the invariant that content outside the
    // expected subtitle region remains identical to the no-ASS render.
    const subtitleComparison = await compareFrames(input.exec, path, input.referencePath, relativeTimestamp);
    const subtitleOutsideComparison = sample.expectedSubtitleBox
      ? await compareFrames(input.exec, path, input.referencePath, relativeTimestamp, [outputBox(sample.expectedSubtitleBox)])
      : subtitleComparison;
    sampledSimilarity = Math.min(sampledSimilarity, evidenceComparison.similarity);
    const threshold = input.contentThreshold ?? 0.98;
    if (!Number.isFinite(threshold) || threshold < 0 || threshold > 1) throw new Error("visual threshold unavailable");
    if (evidenceComparison.similarity < threshold) contentMismatch += 1;
    const cues = input.cues ?? [];
    const activeCue = cues.find((cue) => {
      if (!cue || typeof cue !== "object") return false;
      const item = cue as { start?: unknown; end?: unknown };
      return typeof item.start === "number" && typeof item.end === "number" && relativeTimestamp >= item.start && relativeTimestamp < item.end;
    });
    const expectedText = normalizedText(sample.expectedSubtitleText);
    if (expectedText) {
      if (!activeCue || typeof (activeCue as { text?: unknown }).text !== "string" || normalizedText((activeCue as { text: string }).text) !== expectedText) throw new Error("visual subtitle text mismatch");
      if (!input.assPath) throw new Error("visual subtitle annotation unavailable");
      if (!subtitleComparison.difference) throw new Error("visual subtitle pixels unavailable");
      if (sample.expectedSubtitleBox) {
        const expectedBox = outputBox(sample.expectedSubtitleBox);
        if (overlap(subtitleComparison.difference, expectedBox) / Math.max(EPSILON, area(subtitleComparison.difference)) < 0.8) throw new Error("visual subtitle bbox outside expected region");
      }
      if (subtitleOutsideComparison.similarity < 0.95) contentMismatch += 1;
    } else if (activeCue) {
      throw new Error("unexpected visual subtitle cue");
    } else if (subtitleComparison.difference || subtitleComparison.similarity < 0.98) {
      contentMismatch += 1;
    }
    const protectedBoxes = sample.protectedExistingCaptionBoxes.flatMap((box) => maps.map(({ map }) => map(box)));
    if (subtitleComparison.difference && protectedBoxes.some((box) => overlap(subtitleComparison.difference!, box) > 0)) subtitleOverlap += 1;
    const subjectFailures = sample.requiredSubjectBoxes.filter((box) => annotatedVisibility(box, maps, input.cropPlan?.source ?? null) < 0.9).length;
    const textFailures = sample.requiredTextBoxes.filter((box) => annotatedVisibility(box, maps, input.cropPlan?.source ?? null) < 0.9).length;
    requiredSubjectClipped += subjectFailures;
    requiredTextClipped += textFailures;
  }
  const contentMatch = contentMismatch === 0 ? 1 : 0;
  return { subtitleOverlap, requiredTextClipped, requiredSubjectClipped, focalFailures: requiredSubjectClipped, approvedMomentRetained: contentMatch, approvedWindowOverlap: sampledSimilarity, contentMatch, visualMeasured: true };
}
